version: "3.8"

services:
  aa-client:
    image: aa-client:latest
    container_name: aa-client
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - aa-network

networks:
  aa-network:
    driver: bridge
